name: build develop
on:
  push:
    branches: ["develop", "master"]
  pull_request:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4
        
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile --immutable --prefer-offline

      - name: 🧪 Unit tests
        run: yarn test

      - name: ⚙️ Typescript build
        run: yarn build

      - name: ⚙️ Sample build
        run: |
          cd samples
          yarn install --frozen-lockfile --immutable --prefer-offline
          yarn tsc
          yarn vite build

